### PR TITLE
remove pager; add install.sh

### PR DESCRIPTION
**Pull request by liuyang1**
just share my change to check it's useful or not.

### CODE REVIEW

**Comment by lilydjwg** [comment]
Why do you want to remove pager?

**Comment by liuyang1** [comment]
- I just think le this determined by user, but not by script. This should be better.
- Sometimes, we want to keep searched result in terminal for further check. However, pager will clean searched result. 

That's why I make this change.

**Comment by lilydjwg** [comment]
* the user can override this.
* the default (`-X`) won't.

One thing I like git and systemd is it uses a pager by default, so I don't need to rerun to see the beginning of output. Search results are usually big (several pages or even hundreds).

**Comment by liuyang1** [comment]
Understand now. I will delete the pager part.

**Pull request closed without merging**
